// How many distinct terms are in the sequence generated by ab for 2 < a < 100 and 2 < b < 100?
use std::collections::HashMap;

extern crate num_bigint;
extern crate num_traits;

use num_bigint::{BigUint};
use num_traits::pow;

fn distinct_powers(a: u32, b: usize) -> u32 {

    let mut power: BigUint;
    let mut powers: HashMap<BigUint, bool> = HashMap::new();
    let mut count: u32 = 0;
    
    for i in 2..a+1 {
        for j in 2..b+1 {
            power = pow::pow(i.into(), j);
            // println!("{}", power);
            if !powers.contains_key(&power) {
                powers.insert(power, true);
                count += 1;
            }
        }
    }

    return count;
}

fn main() {

    println!("{}", distinct_powers(100, 100));
}
   
