// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million,
// find the sum of the even-valued terms.

fn fibonacci_sum(limit: i32) -> i32 {

    let (mut a, mut b, mut s, mut c) = (1,1,0, 0);

    loop {
        c = a + b;
        a = b;
        b = c;
        if c >= limit { break; }
        if c % 2 == 0 {
            s += c;
        }

    }

    s
}

fn main() {
    println!("{}", fibonacci_sum(1000000));
}
      
